objects=1_eje 2_eje 3_eje 5_eje 6_eje 7_eje 9_eje 10_eje 12_eje 13_eje 14_eje 15_eje

all: $(objects)

1_eje: 1_eje.c
	gcc -Wall -o 1_eje 1_eje.c
2_eje: 2_eje.c
	gcc -Wall -o 2_eje 2_eje.c
3_eje: 3_eje.c
	gcc -Wall -o 3_eje 3_eje.c
5_eje: 5_eje.c
	gcc -Wall -o 5_eje 5_eje.c
6_eje: 6_eje.c
	gcc -Wall -o 6_eje 6_eje.c
7_eje: 7_eje.c
	gcc -Wall -o 7_eje 7_eje.c
9_eje: 9_eje.c
	gcc -Wall -o 9_eje 9_eje.c
10_eje: 10_eje.c
	gcc -Wall -o 10_eje 10_eje.c
12_eje: 12_eje.c
	gcc -Wall -o 12_eje 12_eje.c        
13_eje: 13_eje.c
	gcc -Wall -o 13_eje 13_eje.c        
14_eje: 14_eje.c
	gcc -Wall -o 14_eje 14_eje.c        
15_eje: 15_eje.c
	gcc -Wall -o 15_eje 15_eje.c 
	                      
clean: 
	-rm -f *.o $(objects)
